apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qdrant-storage-qdrant-test-restore-0
spec:
  dataSource:
    name: qdrant-snapshot-0
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qdrant-storage-qdrant-test-restore-1
spec:
  dataSource:
    name: qdrant-snapshot-1
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qdrant-storage-qdrant-test-restore-2
spec:
  dataSource:
    name: qdrant-snapshot-2
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
