apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qdrant-storage-qdrant-test-0
  namespace: qdrant
spec:
  dataSource:
    name: qdrant-snapshot-0
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qdrant-storage-qdrant-test-1
  namespace: qdrant
spec:
  dataSource:
    name: qdrant-snapshot-1
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qdrant-storage-qdrant-test-2
  namespace: qdrant
spec:
  dataSource:
    name: qdrant-snapshot-2
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
